name: is4wfw wiki

on:
  push:
    tags:
    - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Pack & release
    steps:
      - uses: actions/checkout@v2

      - name: Prepare versions
        id: versions
        run: |
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "::set-output name=TAG_NAME::$TAG_NAME"
        shell: bash
      
      - name: Install composer
        run: ./tools/Install-Composer.ps1
        shell: pwsh
      
      - name: Update version
        run: ./tools/Update-Version.ps1 ${{ steps.versions.outputs.tag_name }}
        shell: pwsh

      - name: Zip artifact
        run: 7z a -tzip is4wfw-wiki-${{ steps.versions.outputs.tag_name }}.zip -w src/.
      
      - name: Prepare release
        uses: ncipollo/release-action@v1.7.1
        with:
          allowUpdates: true
          draft: true
          replacesArtifacts: true
          artifacts: './is4wfw-wiki-${{ steps.versions.outputs.tag_name }}.zip'
          prerelease: ${{ contains(steps.versions.outputs.tag_name, 'preview') }}
          artifactContentType: 'application/x-zip-compressed'
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish release
        uses: ncipollo/release-action@v1.7.1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          replacesArtifacts: false
          prerelease: ${{ contains(steps.versions.outputs.tag_name, 'preview') }}
          token: ${{ secrets.GITHUB_TOKEN }}
